// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCloudPBChange();
void onCloudADCParamChange();

bool cloudPB;
String cloudSamples;
String cloudADCParam;

void initProperties() {
  ArduinoCloud.addProperty(cloudADCParam, READWRITE, 1 * SECONDS, onCloudADCParamChange);
  ArduinoCloud.addProperty(cloudSamples, READ, 1 * ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudPB, READWRITE, ON_CHANGE, onCloudPBChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);